version: '3.8'

services:
  neo4j:
    image: neo4j:5
    volumes:
      - ./csv:/var/lib/neo4j/import
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4JLABS_PLUGINS=["apoc"]
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - '7474:7474'
      - '7687:7687'
    healthcheck:
      test: ['CMD', 'wget', 'http://localhost:7474/', '-O', '-']
      interval: 5s
      timeout: 5s
      retries: 10


  springboot-app:
    image: demographql:latest  # Reemplaza esto con el nombre de tu imagen de Spring Boot si ya la tienes
    build:
     context: .
     dockerfile: ./Dockerfile #
    environment:
      - SPRING_DATASOURCE_URL=bolt://neo4j:7687 # URL de conexión a Neo4j
      - SPRING_DATASOURCE_USERNAME=neo4j
      - SPRING_DATASOURCE_PASSWORD=${NEO4J_PASSWORD}
    depends_on:
      neo4j:
        condition: service_healthy  # Espera a que Neo4j esté saludable
    ports:
      - '8080:8080'